## Scripting-Based Questions

1.	Write a program to take a name and age from the user and print a greeting message.
2.	Create a list of numbers and print only even numbers using a for loop.
3.	Write a program that handles division by zero using try-except.
4.	Given a string, count how many vowels it has.
5.	Reverse a list without using built-in functions.
6.	Create a dictionary with at least 5 key-value pairs and print them.
7.	Write a Pandas code to read a CSV and print the top 5 rows.
8.	Create a DataFrame from a Python dictionary.
9.	Replace all missing values in a DataFrame with the column’s mean.
10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

1.Write a program to take a name and age from the user and print a greeting message.

In [1]:
User_Name = input("Please Enter your name - ")
User_Age = input("Please Enter your age - ")
print("Welcome {}, you are {} years old!!".format(User_Name,User_Age))

Please Enter your name -  Jeeva
Please Enter your age -  25

Welcome Jeeva, you are 25 years old!!

#### 2.Create a list of numbers and print only even numbers using a for loop.

In [2]:
Numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
Even_Number = [x for x in Numbers if x % 2 == 0]
print("Even Number - ",Even_Number)

Even Number -  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

#### 3.Write a program that handles division by zero using try-except.

In [3]:
User_Input = int(input ("Enter the  dividend Number"))
Divisor = int(input ("Enter the  divisor Number"))
try:
  result= User_Input/Divisor
  print (result)
except ZeroDivisionError:
  print("Invalid Divisor")

Enter the  dividend Number 5
Enter the  divisor Number 0

Invalid Divisor

#### 4.Given a string, count how many vowels it has.

In [4]:
User_Input = input("Please enter the word")
User_Input_length = len(User_Input)
#print(User_Input_length)
vowels_count = 0

for i in range(User_Input_length):
    if User_Input[i].lower() in ['a','e','i','o','u']:
        vowels_count += 1
if vowels_count != 0:       
    print("The Vowels count for the given word {} is {}".format(User_Input,vowels_count))
else:
    print("Sorry! the given word {} has no vowels on it".format(User_Input))

Please enter the word jeeva

The Vowels count for the given word jeeva is 3

#### 5.Reverse a list without using built-in functions.

In [5]:
Student_Id = [32,55,66,23,88]
Stud_Length = len(Student_Id)-1
Stud_Rev = []
for i in range(Stud_Length,-1,-1):
  Stud_Rev.append(Student_Id[i])

print(Stud_Rev)

[88, 23, 66, 55, 32]

#### 6.Create a dictionary with at least 5 key-value pairs and print them.

In [6]:
Stud_Marks_In_Maths = {"Jeeva":89, "Raj": 75, "Gugan": 95, "Harry": 65, "Potter": 88}
print(Stud_Marks_In_Maths)
print(type(Stud_Marks_In_Maths))

{'Jeeva': 89, 'Raj': 75, 'Gugan': 95, 'Harry': 65, 'Potter': 88}
<class 'dict'>

#### 7.Write a Pandas code to read a CSV and print the top 5 rows.

In [7]:
import pandas as pd
Sales_Transactions = pd.read_csv("Sales-Transactions-Edited.csv")
Sales_Transactions.head(5)

       Date  Voucher               Party            Product  Qty    Rate
0  1/4/2017        1    SOLANKI PLASTICS      DONA-VAI-9100    2  1690.0
1  1/4/2017        1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1620.0
2  1/4/2017        2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500    23.0
3  1/4/2017        2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1620.0
4  1/4/2017        2  SARNESWARA TRADERS      DONA-VAI-9100    5  1690.0

#### 8.Create a DataFrame from a Python dictionary.

In [8]:
Student_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Subject":["Tamil","English","Maths","Science","Social"],
    "Marks":[88,77,22,99,78]
}

pd.DataFrame(Student_Data)

  Student Name  Subject  Marks
0        Jeeva    Tamil     88
1          Raj  English     77
2         Ramu    Maths     22
3         Somu  Science     99
4        Harry   Social     78

#### 9.Replace all missing values in a DataFrame with the column’s mean.

In [13]:
Student_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Subject":["Tamil","English","Maths","Science","Social"],
    "Marks":[88,77,None,99,78]
}

Stu_DataFrame = pd.DataFrame(Student_Data)
print(Stu_DataFrame,'\n')
print(Stu_DataFrame.isna().sum(),"\n")
Stu_DataFrame.Marks.mean().astype(int)
Stu_DataFrame.Marks = Stu_DataFrame.Marks.fillna(Stu_DataFrame.Marks.mean()).astype(int)
print(Stu_DataFrame)

  Student Name  Subject  Marks
0        Jeeva    Tamil   88.0
1          Raj  English   77.0
2         Ramu    Maths    NaN
3         Somu  Science   99.0
4        Harry   Social   78.0

Student Name    0
Subject         0
Marks           1
dtype: int64

  Student Name  Subject  Marks
0        Jeeva    Tamil     88
1          Raj  English     77
2         Ramu    Maths     85
3         Somu  Science     99
4        Harry   Social     78

#### 10.Filter rows in a DataFrame where the "Age" column is greater than 30.

In [10]:
Student_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Subject":["Tamil","English","Maths","Science","Social"],
    "Marks":[88,77,22,99,78],
    "Age":[17,18,16,32,35]
}

Stu_DataFrame = pd.DataFrame(Student_Data)
print(Stu_DataFrame,'\n')

Stu_DataFrame_Result = Stu_DataFrame[Stu_DataFrame["Age"] > 30]
print(Stu_DataFrame_Result)

  Student Name  Subject  Marks  Age
0        Jeeva    Tamil     88   17
1          Raj  English     77   18
2         Ramu    Maths     22   16
3         Somu  Science     99   32
4        Harry   Social     78   35

  Student Name  Subject  Marks  Age
3         Somu  Science     99   32
4        Harry   Social     78   35